# generate_client_certs.yml
- name: Create client key
  command: "openssl genrsa -out {{ temp_path }}/key.pem 4096"
  changed_when: false

- name: Create client CSR
  command: "openssl req -subj '/CN=client' -new -key {{ temp_path }}/key.pem -out {{ temp_path }}/client.csr"
  changed_when: false

- name: Remove extfile
  file:
    state: absent
    path: "{{ extfile }}"

- name: Create extfile
  file:
    state: touch
    path: "{{ extfile }}"
    mode: 0755

- name: Add extendedKeyUsage to extfile
  lineinfile:
    dest: "{{ extfile }}"
    line: "extendedKeyUsage = clientAuth"
  changed_when: false

- name: Create the client certificate
  command: >-
    openssl x509 -req -days 365 -sha256 -in {{ temp_path }}/client.csr
    -CA {{ temp_path }}/ca.pem -CAkey {{ temp_path }}/ca-key.pem
    -CAcreateserial -out {{ temp_path }}/cert.pem -extfile {{ extfile }}
    -passin file:{{ passphrase_file }}
  changed_when: false

- name: Check that the client cert path exists
  file:
    state: directory
    path: "{{ client_cert_path }}"
    mode: 0755
  changed_when: false

- name: Copy client certs
  command: cp "{{ temp_path }}/{{ item }}" "{{ client_cert_path }}/."
  with_items:
    - ca.pem
    - cert.pem
    - key.pem
  changed_when: false

# Read-Only to avoid issues
- name: Set file permissions
  file:
    path: "{{ client_cert_path }}/{{ item }}"
    mode: 0444
  with_items:
    - ca.pem
    - cert.pem
    - key.pem
